### ISSUE TITLE
运行点击登录后崩溃 

### ISSUE THREAD

**Issue by macaliu** [sunfengqi8023/LoginForSoapAndRxjava#1]
日志如下
`12-14 23:51:59.901 31743-1565/com.mr_sun.logindemo E/AndroidRuntime: FATAL EXCEPTION: RxIoScheduler-2
                                                                     Process: com.mr_sun.logindemo, PID: 31743
                                                                     java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
                                                                         at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:62)
                                                                         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
                                                                         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                         at java.lang.Thread.run(Thread.java:818)
                                                                      Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lio/bugtags/agent/instrumentation/okhttp3/OkHttp3Instrumentation;
                                                                         at retrofit2.RequestBuilder.build(RequestBuilder.java:222)
                                                                         at retrofit2.ServiceMethod.toRequest(ServiceMethod.java:112)
                                                                         at retrofit2.OkHttpCall.createRawCall(OkHttpCall.java:178)
                                                                         at retrofit2.OkHttpCall.execute(OkHttpCall.java:162)
                                                                         at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:171)
                                                                         at rx.internal.operators.OperatorSubscribeOn$1$1$1.request(OperatorSubscribeOn.java:80)
                                                                         at rx.Subscriber.setProducer(Subscriber.java:211)
                                                                         at rx.internal.operators.OperatorSubscribeOn$1$1.setProducer(OperatorSubscribeOn.java:76)
                                                                         at rx.Subscriber.setProducer(Subscriber.java:205)
                                                                         at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:152)
                                                                         at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:138)
                                                                         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
                                                                         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                                                                         at rx.Observable.unsafeSubscribe(Observable.java:8666)
                                                                         at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
                                                                         at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:220)
                                                                         at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                                         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
                                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154) 
                                                                         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269) 
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                         at java.lang.Thread.run(Thread.java:818) 
                                                                      Caused by: java.lang.ClassNotFoundException: Didn't find class "io.bugtags.agent.instrumentation.okhttp3.OkHttp3Instrumentation" on path: DexPathList[[zip file "/data/app/com.mr_sun.logindemo-1/base.apk"],nativeLibraryDirectories=[/data/app/com.mr_sun.logindemo-1/lib/arm, /system/lib, /vendor/lib, system/vendor/lib, system/vendor/lib/egl, system/lib/hw]]
                                                                         at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                         at retrofit2.RequestBuilder.build(RequestBuilder.java:222) 
                                                                         at retrofit2.ServiceMethod.toRequest(ServiceMethod.java:112) 
                                                                         at retrofit2.OkHttpCall.createRawCall(OkHttpCall.java:178) 
                                                                         at retrofit2.OkHttpCall.execute(OkHttpCall.java:162) 
                                                                         at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:171) 
                                                                         at rx.internal.operators.OperatorSubscribeOn$1$1$1.request(OperatorSubscribeOn.java:80) 
                                                                         at rx.Subscriber.setProducer(Subscriber.java:211) 
                                                                         at rx.internal.operators.OperatorSubscribeOn$1$1.setProducer(OperatorSubscribeOn.java:76) 
                                                                         at rx.Subscriber.setProducer(Subscriber.java:205) 
                                                                         at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:152) 
                                                                         at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:138) 
                                                                         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50) 
                                                                         at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) 
                                                                         at rx.Observable.unsafeSubscribe(Observable.java:8666) 
                                                                         at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94) 
                                                                         at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:220) 
                                                                         at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55) 
                                                                         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
                                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154) 
                                                                         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269) 
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                         at java.lang.Thread.run(Thread.java:818) 
                                                                     	Suppressed: java.lang.ClassNotFoundException: io.bugtags.agent.instrumentation.okhttp3.OkHttp3Instrumentation
                                                                         at java.lang.Class.classForName(Native Method)
                                                                         at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                         at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                         		... 25 more
                                                                      Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available`

**Comment by macaliu** [comment]
不好意思 误报 已找到原因
